FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

RUN mkdir /var/www/laravel/public -p && touch /var/www/laravel/public/index.php
# COPY html /usr/share/nginx/html

# ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "nginx", "-g" , "daemon off;" ]

# nginx -g  daemon off;

# docker build -t vsantos98/nginx:prod . -f Dockerfile.prod

# docker run -d --network laranet --name nginx -p 8080:80 vsantos98/nginx:prod